#! /bin/bash

if [[ -z $1 ]]
    then
        x-terminal-emulator -e ./src/fat.bin
    else
        if (( $# > 1 ))
            then
                echo "Too many arguments"
            else
                x-terminal-emulator -e ./src/fat.bin "$1"
        fi
fi
